apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd  # ArgoCD가 설치된 네임스페이스
spec:
  project: default
  source:
    repoURL: https://github.com/eunyuljo/argo-cd-helm  # Git 저장소 URL로 변경
    targetRevision: HEAD  # 기본적으로 최신 커밋을 사용할 경우 HEAD로 지정 (특정 브랜치명도 가능)
    path: .  # 현재 디렉토리에서 차트를 찾는다면 '.'로 지정, 서브 디렉토리라면 그 경로를 입력
    helm:
      releaseName: argocd  # 배포할 릴리스 이름
      valueFiles:
        - values.yaml  # 사용할 values.yaml 파일
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
